# Generated by Django 4.2.5 on 2023-09-11 12:11

from django.conf import settings
from django.db import migrations, models
import social_app.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=social_app.models.avatar_image_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="followed",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
