# Generated by Django 4.2.5 on 2023-09-13 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0003_alter_profile_avatar_alter_profile_followed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="owner",
        ),
    ]
