# Generated by Django 4.2.5 on 2023-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0004_rename_user_profile_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.CharField(default=1, max_length=511),
            preserve_default=False,
        ),
    ]
