# Generated by Django 4.2.5 on 2023-09-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0005_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followed",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="social_app.profile"
            ),
        ),
    ]
